(define (add-interval x y)
   (make-interval (+ (lower-bound x) (lower-bound y))
                  (+ (upper-bound x) (upper-bound y))))
(define (interval-width x) (/ (- (upper-bound x) (lower-bound x)) 2))

(define (mul-interval x y)
   (let ((p1 (* (lower-bound x) (lower-bound y)))
         (p2 (* (lower-bound x) (upper-bound y)))
         (p3 (* (upper-bound x) (lower-bound y)))
         (p4 (* (upper-bound x) (upper-bound y))))
     (make-interval (min p1 p2 p3 p4)
                    (max p1 p2 p3 p4))))
(= (interval-width (add-interval x y))
   (+ (interval-width x) (interval-width y)))
(= (interval-width (mul-interval x y))
   (* (interval-width x) (interval-width y)))

