(define (make-point x y) (cons x y))
(define (x-pt a) (car a))
(define (y-pt a) (cdr a))
(define (print-point x)
   (newline)
   (display "(")
   (display (x-pt x))
   (display ",")
   (display (y-pt x))
   (display ")"))
(define (make-segment start end)
        (cons start end))
(define (start-segment segment) (car segment))
(define (end-segment segment) (cdr segment))
(define (midpoint-segment segment)
   (make-point (/ (+ (car (start-segment segment)) (car (end-segment segment))) 2)
               (/ (+ (cdr (start-segment segment)) (cdr (end-segment segment))) 2)))
         
