(define (smallest-divisor n)
   (find-divisor n 2)
(define (find-divisor n test-divisor)
   (cond ((> (square test-divisor) n) n)
         ((divides? test-devisor n) test-divisor)
         (else (find-divisor n (+ test-divisor 1)))))(define (divides? a b)
   (= (remainder b a) 0))
(define (prime? n)
   (= n (smallest-divisor n)))
(smallest-divisor 199)
